---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 17.05.2020 22:30
---

function AnyHPEARandomBuild(x, y,id)
	AdjustPlayerStateBJ(1000, Player(1), PLAYER_STATE_RESOURCE_LUMBER)
	AdjustPlayerStateBJ(1000, Player(1), PLAYER_STATE_RESOURCE_GOLD)
	--print(id)
	for i = 1, 5 do
		local r = GetRandomInt(-800, 800)
		local builder = FindUnitOfType(FourCC('opeo'), 2500, x, y)
		IssueBuildOrderById(builder, id, x , y )
		if i == 1 then
			r=0
		end
		--PingMinimap(GetUnitX(builder),GetUnitY(builder),1)
		if IssueBuildOrderById(builder, id, x + r, y + r) then
		--	print("Иду строить")
			IssueImmediateOrder(builder, "repairon")
		else
			if i>=5 then
				IssueImmediateOrder(builder, "autoharvestgold")
			else
				IssueImmediateOrder(builder, "autoharvestlumber")
			end
		end
		TimerStart(CreateTimer(), 2, true, function()
			--print(OrderId2String(GetUnitCurrentOrder(builder)))
			if OrderId2String(GetUnitCurrentOrder(builder))=="harvest" then
				IssueImmediateOrder(builder, "autoharvestlumber")
				DestroyTimer(GetExpiredTimer())
			end
		end)
	end
end
