---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 15.06.2020 2:24
---

function InitMap()
	local hero=FindUnitOfType(HeroID)
	SelectUnitForPlayerSingle(hero,GetOwningPlayer(hero))
	OnAttack()
	InitUnitDeathMap()
	local text=CreateBigText("Не дайте пеонам сбежать",3)
	TimerStart(CreateTimer(), 20, true, function()
		BlzDestroyFrame(text)
	end)
	CreatePeonCountFrame()
	CreateGlue()
end

function CreateGlue()
	local next=0.039
	local  buttonFrame = BlzCreateFrameByType("GLUEBUTTON", "FaceButton", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
	local  buttonIconFrame = BlzCreateFrameByType("BACKDROP", "FaceButtonIcon", buttonFrame, "", 0)
	BlzFrameSetAllPoints(buttonIconFrame, buttonFrame)
	BlzFrameSetTexture(buttonIconFrame, "ReplaceableTextures\\CommandButtons\\BTNSelectHeroOn", 0, true)
	BlzFrameSetSize(buttonFrame,next,next)
	BlzFrameSetAbsPoint(buttonFrame,FRAMEPOINT_CENTER,next/2,0.17)
	local  this = CreateTrigger()
	BlzTriggerRegisterFrameEvent(this, buttonFrame, FRAMEEVENT_CONTROL_CLICK)
	local mark=MarkSystem
	TriggerAddAction(this, function ()
		BlzFrameSetEnable(buttonFrame, false)
		BlzFrameSetEnable(buttonFrame, true)
		if mark then
			MarkSystem=false
			print("маркеры выключены")
			mark=false
		else
			mark=true
			MarkSystem=true
			print("маркеры включены")
		end
	end)
end