---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 10.06.2020 16:23
---
function CreateBigText(text,maxSize)
	local newText = BlzCreateFrameByType("TEXT", "", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
	BlzFrameSetText(newText, text)
	BlzFrameSetAbsPoint(newText,FRAMEPOINT_CENTER,0.4,0.55)
	BlzFrameSetScale(newText, maxSize)
	return newText
end