---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 10.06.2020 16:39
---

function OnAttack()
	local this = CreateTrigger()
	TriggerRegisterAnyUnitEventBJ(this, EVENT_PLAYER_UNIT_ATTACKED)
	TriggerAddAction(this, function()
		local hero=GetTriggerUnit()--тот кто атакован

		if GetUnitTypeId(hero)==FourCC('opeo') then
			local boat=FindUnitOfType(FourCC('obot'))
			if GetUnitCurrentOrder(hero)~=String2OrderIdBJ("smart") then
				IssueTargetOrder(hero,"smart",boat)
			end
		end
	end)
end