---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 26.05.2020 0:51
---
HeroID=FourCC("H000")--ID героя Адмирала пирата
SpellIDQ=FourCC("A000") -- Выстрел из мушкета
SpellIDW=FourCC("A001") -- Бросок якоря
SpellIDE=FourCC("A002") -- Удар саблей
SpellIDR=FourCC("A003") -- Пушки из ларца